server:
  port: 8081

spring:
  application:
    name: projeto-integrador-ii-barbearia
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/barbearia
    username: aluno
    password: mysql
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  sql:
      init:
          mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: hbhousebarber@gmail.com
    password: upfsonixrzaeedzo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 284619409068-qaljhs8mf3va5tu6kg05o7qduuf8rp0h.apps.googleusercontent.com
            client-secret: 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
            scope: https://www.googleapis.com/auth/gmail.send

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

auth:
  jwt-secret: PROJETOINTEGRADORBARBEARIARV13D47F565B6DECC3N7R4L1Z4D0RV1AS0F7N3X74G336000000F1NT3C4HU3D47F565B6DEC
  #24 horas
  jwt-expiration-miliseg: 86400000
  token-forgot-password: TLGqJAPC0UdCWceNoCeiIJKtwwBIey3G
  public-sing-up-url-enable: false

#hbhousebarber@gmail.com
#Barbearia123$